(function () {
  "use strict";
  window.LEARNING_DATA = {
    version: "2026.07",
    profiles: [
      { id: "new", label: "New to electrical engineering", note: "Start with maths, circuits and three-phase quantities before modelling." },
      { id: "electrical", label: "Electrical engineer new to power-system studies", note: "Use Foundation Zero, then move through the study methods in order." },
      { id: "pf", label: "Power-system engineer new to PowerFactory", note: "Start with the PowerFactory practitioner route and keep hand checks alongside every run." },
      { id: "protection", label: "PowerFactory user new to protection", note: "Build fault-method confidence before coordination and settings work." },
      { id: "connection", label: "PowerFactory user new to UK grid connections", note: "Follow the connection route alongside the study-method chapters it depends on." },
      { id: "reference", label: "Experienced engineer using the site as a reference", note: "Use the diagnostic to identify a focused refresher; no content is locked." }
    ],
    objectives: [
      { id: "fundamentals", label: "Build strong fundamentals", path: "A" },
      { id: "loadflow", label: "Learn load-flow studies", path: "B" },
      { id: "fault", label: "Learn fault analysis", path: "C" },
      { id: "protection", label: "Learn protection coordination", path: "D" },
      { id: "powerfactory", label: "Learn PowerFactory comprehensively", path: "E" },
      { id: "dynamics", label: "Learn dynamic studies", path: "F" },
      { id: "connection", label: "Learn UK grid-connection studies", path: "G" },
      { id: "complete", label: "Complete the professional pathway", path: "H" }
    ],
    paths: [
      { id: "A", name: "Electrical and power-system foundations", audience: "Learners building the theory needed to read a network and check a model.", prerequisite: "No power-system background assumed; Foundation Zero is required.", chapters: [1,2,3,4,5], hours: 42, labs: ["Mini-3B benchmark model", "Equipment-data and topology QA"], assessments: ["Foundation diagnostic", "Three-phase and per-unit check", "Model QA judgement"], portfolio: ["Annotated SLD", "Units/base sheet", "model QA record"], outcome: "Explain core quantities, convert bases, read an SLD and identify missing model data.", standard: "Complete the hand checks and demonstrate one controlled baseline model with a stated data limitation." },
      { id: "B", name: "Load flow and steady-state studies", audience: "Engineers who need to model operating cases, voltage and thermal performance.", prerequisite: "Path A or equivalent electrical fundamentals.", chapters: [2,3,4,5,6,7,8,9,10], hours: 58, labs: ["AC load flow", "Q-limit behaviour", "N-1/contingency envelope"], assessments: ["Load-flow diagnostic clinic", "Voltage/thermal numerical check", "study conclusion"], portfolio: ["Scenario schedule", "load-flow result extract", "voltage/thermal conclusion"], outcome: "Build credible steady-state cases, diagnose implausible solutions and report a decision.", standard: "Retain a named Study Case, independent check and a conclusion with limit/margin." },
      { id: "C", name: "Fault analysis", audience: "Engineers assessing fault duties and protection sensitivity.", prerequisite: "Path A; use Path B modelling discipline before Complete-method work.", chapters: [2,3,4,11,12,13,14,15], hours: 58, labs: ["IEC 60909 maximum/minimum faults", "sequence and earthing paths", "duty comparison"], assessments: ["Thevenin calculation", "method-selection judgement", "fault-result reconciliation"], portfolio: ["Fault-case register", "duty schedule", "method disclosure"], outcome: "Select and disclose an appropriate fault method and interpret fault duties without conflating methods.", standard: "Compare one hand screen with a controlled software case through an error budget." },
      { id: "D", name: "Protection coordination", audience: "Engineers learning relay application and coordination rather than memorising settings.", prerequisite: "Path C; CT/VT and minimum-fault concepts are required.", chapters: [12,13,14,15,16,17,18], hours: 54, labs: ["Overcurrent/earth-fault coordination", "CT/VT and clearing-time checks", "settings report"], assessments: ["IDMT numerical task", "curve/coordination clinic", "protection recommendation"], portfolio: ["Settings schedule", "coordination plot", "protection philosophy"], outcome: "Check pickup, timing, sensitivity, selectivity and backup against documented inputs.", standard: "No universal settings: retain CT data, min/max faults, breaker time and agreed criterion." },
      { id: "E", name: "PowerFactory practitioner", audience: "Engineers building reproducible model and calculation workflows.", prerequisite: "Electrical foundations; study-method chapters run in parallel.", chapters: [3,4,5,6,12,16,21,24,30,31], hours: 64, labs: ["Mini-3B build", "Study Case/scenario/variation control", "result extraction and automation"], assessments: ["Object mapping", "reproducibility challenge", "model QA review"], portfolio: ["Project hierarchy record", "version/change log", "QA checklist"], outcome: "Use the software as a controlled engineering environment, not a drawing package.", standard: "Reopen the model and reproduce a named result with controlled inputs and an independent check." },
      { id: "F", name: "Dynamic studies", audience: "Engineers progressing from steady state to RMS event studies.", prerequisite: "Paths A and B; basic fault and control knowledge recommended.", chapters: [6,7,12,19,20,21,22,23,24], hours: 52, labs: ["Initialisation/no-disturbance", "event sequence", "frequency and voltage response"], assessments: ["Swing-equation screen", "RMS result clinic", "model-limit judgement"], portfolio: ["Event schedule", "plots", "validation/limitation statement"], outcome: "Prepare, run and interpret introductory RMS studies while separating stability from compliance.", standard: "Pass a no-disturbance gate and retain model/version/initialisation evidence before interpreting an event." },
      { id: "G", name: "UK grid-connection engineer", audience: "Engineers scoping GB connection studies and compliance evidence.", prerequisite: "Paths A and B; C/D/F depend on project scope.", chapters: [1,5,6,9,10,12,16,19,21,24,25,26,27,28,29,32], hours: 72, labs: ["G98/G99 route screen", "requirements/assumptions register", "compliance evidence mapping"], assessments: ["Applicability map", "study-scope judgement", "compliance matrix review"], portfolio: ["Scope", "source/assumption register", "compliance matrix"], outcome: "Define a study scope and evidence plan without treating guidance or generic values as universal requirements.", standard: "Tie every conclusion to an applicable, dated source and project boundary; escalate ambiguity." },
      { id: "H", name: "Complete professional pathway", audience: "A deliberate, broad development route for engineers preparing a complete training study package.", prerequisite: "Commit to the full sequence; prior experience can shorten review but not evidence quality.", chapters: Array.from({ length: 32 }, (_, i) => i + 1), hours: 306, labs: ["All core labs", "continuing training project", "capstone package"], assessments: ["Module reviews", "integrated clinics", "capstone self-review"], portfolio: ["Controlled model record", "study package", "technical report"], outcome: "Connect physics, method, software, validation, requirements and reporting across an integrated project.", standard: "Training evidence only: obtain competent review before using any method/result in live project work." }
    ],
    diagnostic: [
      { id: "power", prompt: "At 11 kV, which relationship gives balanced three-phase current from apparent power?", options: ["I = S/(sqrt(3) VLL)", "I = S/VLL", "I = VLL/(sqrt(3) S)", "I = P x VLL"], answer: 0, tags: ["A","B","C","D","E","F","G"] },
      { id: "model", prompt: "A load flow converges but a cable is grey/de-energised. What is the best first action?", options: ["Accept convergence", "Trace the active electrical path, cubicles and switch states", "Increase iteration limit", "Change all loads to zero"], answer: 1, tags: ["A","B","E"] },
      { id: "fault", prompt: "Which statement is technically sound?", options: ["IEC 60909, G74 and Complete results are interchangeable", "The method, maximum/minimum basis and reported quantity must be stated", "A higher fault level is always safer", "One source short-circuit MVA is enough for every fault"], answer: 1, tags: ["C","D","E","G"] },
      { id: "protection", prompt: "A relay pickup should be checked against:", options: ["Only maximum fault current", "Only cable rating", "Maximum load/inrush and minimum fault current, with CT/VT and time context", "A universal typical setting"], answer: 2, tags: ["D","C"] },
      { id: "dynamics", prompt: "Before interpreting an RMS disturbance result, what is a minimum gate?", options: ["A colourful plot", "Load-flow initialisation and a no-disturbance run with no unexplained issue", "A very short time step only", "A stable result from an unrelated case"], answer: 1, tags: ["F","E"] },
      { id: "connection", prompt: "For a GB connection study, the controlling requirement is determined by:", options: ["A remembered generic limit", "The project classification, connection agreement, applicable code/recommendation and current DNO/TO/NESO process", "The largest rating on the SLD", "Whether the model converges"], answer: 1, tags: ["G","H"] }
    ],
    project: {
      name: "Northmere Energy Park — training network",
      boundary: "Fictional 132/33/11 kV GB network used only for training. It is not a real system, design or connection offer.",
      brief: "Assess a proposed 24 MW / 48 MWh BESS and 12 MW solar plant at Northmere 33 kV. Build a controlled base model; assess intact/N-1 load flow, maximum/minimum faults, protection sensitivity, applicable power-quality/dynamic scope and an evidence-led connection conclusion.",
      assets: ["132 kV External Grid equivalent", "2 x 40 MVA 132/33 kV transformers with OLTCs", "33 kV Northmere busbar and sectionaliser", "33/11 kV 20 MVA transformer", "11 kV industrial and general-demand feeders", "33 kV BESS/solar connection feeder", "shunt reactor/capacitor training placeholder", "CTs, VTs, breakers and feeder/transformer protection placeholders"],
      scenarios: ["S1 maximum demand / minimum embedded generation", "S2 minimum demand / maximum solar export", "S3 maximum BESS export", "S4 transformer T1 outage (training N-1 case)", "S5 minimum-fault configuration", "S6 maximum-fault configuration", "S7 RMS no-disturbance baseline", "S8 RMS fault and cleared-event case"],
      registers: ["Project brief and applicability map", "Source register", "Data/assumption/missing-data register", "Scenario and contingency schedule", "Change log", "Acceptance-criteria and compliance matrix"],
      chapterLinks: { "1-5": "Interpret boundary, units, equipment and controlled model structure.", "6-10": "Build cases; assess voltage, thermal loading, controls and contingencies.", "11-18": "Calculate duties; verify earthing/sequence paths; coordinate protection.", "19-24": "Screen harmonics/P28 and prepare/interpret RMS cases.", "25-29": "Classify requirements and assemble GB connection evidence.", "30-32": "Automate repeatable checks, report and self-review the integrated package." }
    },
    capstone: {
      milestones: ["M1 Scope and controlled evidence", "M2 Model build and QA", "M3 Steady-state envelope", "M4 Faults, duty and protection", "M5 Dynamic/power-quality applicability", "M6 Compliance, risks and report"],
      deliverables: ["Project brief interpretation", "Responsibility and applicability map", "Study scope", "Requirement and acceptance-criteria register", "Source-data register", "Assumptions and limitations", "Controlled SLD", "Equipment and model-data schedule", "Model QA report", "Operating-scenario schedule", "Load-flow results", "Contingency results", "Voltage and thermal assessment", "Maximum and minimum fault-level results", "Equipment-duty assessment", "Protection-coordination study", "Protection settings summary", "Dynamic-study scope and results where applicable", "Power-quality screening where applicable", "Compliance matrix", "Risks and open-data schedule", "Mitigation options", "Recommendations", "Executive summary", "Technical conclusion"],
      rubric: ["Boundary, sources and assumptions are explicit", "Methods match the stated decision and are reproducible", "Results state case, quantity, unit, criterion and margin", "Independent checks and limitations are visible", "Recommendations are proportionate and do not claim unsupported compliance"],
      warning: "This is a training capstone. It is not an approved design, setting file, compliance statement or substitute for competent project review."
    },
    clinic: [
      ["LF-01","Converged but isolated bus","Load flow","A result converges while a feeder is electrically isolated.","Trace cubicles, terminals, switch state and source-to-load path.","Unserved load or false voltage result."],
      ["LF-02","Generator Q limit","Load flow","Generator voltage control switches at a reactive limit.","Check Q limit, sign convention, PV/PQ status and bus voltage.","Incorrect voltage-control conclusion."],
      ["LF-03","OLTC at limit","Load flow","Tap controller sits at maximum/minimum.","Check target, deadband, direction, limits and upstream voltage.","Unregulated voltage or controller conflict."],
      ["LF-04","N-1 thermal overload","Load flow","Transformer exceeds its applicable rating after an outage.","Confirm outage, rating duration/season, load transfer and parallel paths.","Thermal/security claim without correct criterion."],
      ["SC-01","Unexpected earth-fault current","Fault","Earth-fault current is far below the expected value.","Inspect zero-sequence data, transformer vector group and neutral earthing.","Protection sensitivity/duty error."],
      ["SC-02","Fault method mismatch","Fault","A Complete result is compared to an IEC duty limit without disclosure.","Confirm brief, prefault state, method options and compared quantity.","Invalid duty conclusion."],
      ["PR-01","Overlapping curves","Protection","Downstream/upstream protection has insufficient separation.","Check CT basis, pickup, curve, TMS, breaker time, min/max faults and agreed margin.","Loss of selectivity."],
      ["PR-02","Pickup above minimum fault","Protection","A relay is secure on load but insensitive at the remote end.","Check measured fault current, CT ratio, fault path and protection zone.","Failure to clear a credible fault."],
      ["DY-01","Stable but unacceptable recovery","Dynamics","RMS result remains stable but voltage recovery is poor.","Check applicable criterion, model limits, controls, plots and clearing sequence.","Stability incorrectly reported as compliance."],
      ["DY-02","Wrong active variation","Model governance","A result changes after reopening a project.","Record/activate Study Case, scenario, variation, time and saved edits.","Non-reproducible evidence."]
    ].map(([id,title,area,symptom,check,risk]) => ({ id,title,area,symptom,check,risk })),
    templates: [
      ["study-scope","Study scope","md",["Decision and boundary","Applicable requirements and acceptance criteria","Study methods/cases","Exclusions and interfaces","Reviewer/approval route"]],
      ["data-register","Source-data register","csv",["Item","Parameter","Value","Unit","Source","Revision/date","Confidence","Owner","Open action"]],
      ["assumptions","Assumptions and limitations register","csv",["ID","Assumption or limitation","Reason","Study affected","Impact","Validation/action","Owner","Status"]],
      ["scenario","Scenario and contingency schedule","csv",["Case ID","Demand","Generation/BESS","Outage","Control state","Season/time","Purpose","Acceptance criterion"]],
      ["model-qa","Model QA checklist","md",["Topology","Parameters/types","Units and bases","Behaviour","Sensitivity","Reproducibility","Reviewer conclusion"]],
      ["fault-duty","Fault and equipment-duty schedule","csv",["Location","Method","Case","Ik double-prime","Peak","Breaking/thermal quantity","Rating","Margin","Conclusion"]],
      ["protection","Protection settings/coordination schedule","csv",["Asset/function","CT/VT basis","Pickup","Curve/delay","Min fault","Max load/inrush","Breaker time","Criterion","Status"]],
      ["dynamic-events","Dynamic event schedule","csv",["Case","Initialisation","Event/time","Clearing/action","Outputs","Criterion","Model version","Status"]],
      ["compliance","Compliance matrix","csv",["Requirement ID","Classification","Applicable?","Evidence","Boundary/case","Status","Open action","Owner"]],
      ["report-outline","Study report outline","md",["Executive summary","Scope and requirements","Inputs/assumptions","Methods and validation","Results","Limitations/risks","Recommendations","Appendices"]],
      ["review","Independent technical review","md",["Question/criterion","Method and model version","Inputs/sources","Independent check","Finding","Action/owner"]],
      ["cpd","CPD evidence log","csv",["Date","Topic","Hours","Activity","Evidence","Reflection","Workplace application","Next action"]]
    ].map(([id,title,format,fields]) => ({ id,title,format,fields }))
  };
})();
